BEGIN;

CREATE TABLE IF NOT EXISTS staging.mef_devengado (
    ano_eje SMALLINT NOT NULL,
    nivel_gobierno TEXT,
    nivel_gobierno_nombre TEXT,
    sector TEXT,
    sector_nombre TEXT,
    pliego TEXT,
    pliego_nombre TEXT,
    sec_ejec TEXT,
    ejecutora TEXT,
    ejecutora_nombre TEXT,
    departamento_ejecutora TEXT,
    departamento_ejecutora_nombre TEXT,
    provincia_ejecutora TEXT,
    provincia_ejecutora_nombre TEXT,
    distrito_ejecutora TEXT,
    distrito_ejecutora_nombre TEXT,
    programa_ppto TEXT,
    programa_ppto_nombre TEXT,
    tipo_act_proy TEXT,
    producto_proyecto TEXT,
    producto_proyecto_nombre TEXT,
    actividad_accion_obra TEXT,
    actividad_accion_obra_nombre TEXT,
    funcion TEXT,
    funcion_nombre TEXT,
    division_funcional TEXT,
    division_funcional_nombre TEXT,
    grupo_funcional TEXT,
    grupo_funcional_nombre TEXT,
    sec_func TEXT,
    meta TEXT,
    finalidad TEXT,
    meta_nombre TEXT,
    departamento_meta TEXT,
    departamento_meta_nombre TEXT,
    fuente_financiamiento TEXT,
    fuente_financiamiento_nombre TEXT,
    rubro TEXT,
    rubro_nombre TEXT,
    tipo_recurso TEXT,
    tipo_recurso_nombre TEXT,
    categoria_gasto TEXT,
    categoria_gasto_nombre TEXT,
    tipo_transaccion TEXT,
    tipo_transaccion_nombre TEXT,
    generica TEXT,
    generica_nombre TEXT,
    subgenerica TEXT,
    subgenerica_nombre TEXT,
    subgenerica_det TEXT,
    subgenerica_det_nombre TEXT,
    especifica TEXT,
    especifica_nombre TEXT,
    especifica_det TEXT,
    especifica_det_nombre TEXT,
    monto_pia NUMERIC(24, 2) NOT NULL DEFAULT 0,
    monto_pim NUMERIC(24, 2) NOT NULL DEFAULT 0,
    monto_certificado_anual NUMERIC(24, 2) NOT NULL DEFAULT 0,
    monto_comprometido_anual NUMERIC(24, 2) NOT NULL DEFAULT 0,
    monto_devengado_enero NUMERIC(24, 2) NOT NULL DEFAULT 0,
    monto_devengado_febrero NUMERIC(24, 2) NOT NULL DEFAULT 0,
    monto_devengado_marzo NUMERIC(24, 2) NOT NULL DEFAULT 0,
    monto_devengado_abril NUMERIC(24, 2) NOT NULL DEFAULT 0,
    monto_devengado_mayo NUMERIC(24, 2) NOT NULL DEFAULT 0,
    monto_devengado_junio NUMERIC(24, 2) NOT NULL DEFAULT 0,
    monto_devengado_julio NUMERIC(24, 2) NOT NULL DEFAULT 0,
    monto_devengado_agosto NUMERIC(24, 2) NOT NULL DEFAULT 0,
    monto_devengado_septiembre NUMERIC(24, 2) NOT NULL DEFAULT 0,
    monto_devengado_octubre NUMERIC(24, 2) NOT NULL DEFAULT 0,
    monto_devengado_noviembre NUMERIC(24, 2) NOT NULL DEFAULT 0,
    monto_devengado_diciembre NUMERIC(24, 2) NOT NULL DEFAULT 0,
    monto_devengado_anual NUMERIC(24, 2) NOT NULL DEFAULT 0,
    monto_girado_anual NUMERIC(24, 2) NOT NULL DEFAULT 0
);

COMMENT ON TABLE staging.mef_devengado IS
    'Datos consolidados de ejecución presupuestal del MEF para 2024, 2025 y 2026.';

COMMIT;
